#!/bin/bash
set -eu
DBRHINO_AGENT_DEBUG=1 \
DBRHINO_AGENT_SERVER_URL=http://dbrhino.dev1:44044 \
DBRHINO_AGENT_CONFIG_DIR=$HOME/.dbrhino \
DBRHINO_AGENT_LOG_PATH=$HOME/.dbrhino/agent.log \
go run $(ls *.go | grep -v _test) "$@"
